{{- if and .Values.keycloak.enabled .Values.secrets.keycloak.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stratium.keycloakSecretName" . }}
  labels:
    {{- include "stratium.keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.keycloak.auth.adminUser | b64enc | quote }}
  admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
{{- end }}
