{{- if .Values.pap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stratium.pap.serviceName" . }}
  labels:
    {{- include "stratium.pap.labels" . | nindent 4 }}
  {{- with .Values.pap.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.pap.service.type }}
  ports:
  - name: http
    port: {{ .Values.pap.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "stratium.pap.selectorLabels" . | nindent 4 }}
{{- end }}