{{- if and .Values.postgresql.enabled .Values.secrets.postgresql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stratium.postgresqlSecretName" . }}
  labels:
    {{- include "stratium.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  stratium-user: {{ .Values.postgresql.auth.stratiumUser | b64enc | quote }}
  stratium-password: {{ .Values.postgresql.auth.stratiumPassword | b64enc | quote }}
{{- end }}
